# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    pre_build:
      - sphinx-apidoc -e -f --implicit-namespaces -o docs/quri_parts/riqu -M quri_parts/riqu
    post_build:
    #  - python -m sphinx -b html docs $READTHEDOCS_OUTPUT/html
      - ls -lR docs
      - ls -lR $READTHEDOCS_OUTPUT/html
  #commands:
  #  - python -mvirtualenv --system-site-packages $READTHEDOCS_VIRTUALENV_PATH
  #  - python -m pip install --upgrade --no-cache-dir pip setuptools<58.3.0
  #  - python -m pip install --upgrade --no-cache-dir -I pillow mock==1.0.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.9.1 recommonmark==0.5.0 sphinx sphinx-rtd-theme readthedocs-sphinx-ext<2.3 setuptools<58.3.0
  #  - python -m pip install --exists-action=w --no-cache-dir -r docs/requirements.txt
  #  - cd docs && python -m pip install --exists-action=w --no-cache-dir -r requirements.txt
  #  - cd docs && sphinx-apidoc -e -f --implicit-namespaces -o ./quri_parts/riqu -M ../quri_parts
  #  - cd docs && sphinx-build -b html . _build
  #  - cp --recursive docs/_build/* $READTHEDOCS_OUTPUT/html

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - requirements: docs/requirements.txt
  system_packages: true