name: Check licenses of dependencies

on:
  pull_request:
    paths:
      - .licenses/**
      - pyproject.toml
  push:
    branches: [main]
    paths:
      - pyproject.toml
  schedule:
    - cron: '0 0 * * MON-FRI'
  workflow_dispatch:
    branches: [main]

jobs:
  check-licenses:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
        cache-dependency-path: 'pyproject.toml'

    - run: python -m venv venv
    - run: |
        . venv/bin/activate
        pip install -e .

    - uses: jonabc/setup-licensed@v1.1.2
      with:
        version: '3.x'
        github_token: ${{ secrets.GITHUB_TOKEN }}
    
    - run: licensed cache
    - run: licensed status
