name: Test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python -
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'poetry'

    - uses: Gr1N/setup-poetry@v8
      env:
        POETRY_VERSION: "1.4.2"

    - run: |
        poetry install -vvv

    - run: poetry run pytest
